version: '3.2'

services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: cvpage_dev
        ports:
            - "5432:5432"
